### ISSUE TITLE
Improved document type names

### ISSUE THREAD

**Issue by phax** [phax/phoss-directory#13]
Suggestion from Anders:

A small remark; it looks you're using a "non standard" reference to the PEPPOL messages that the PEPPOL user has the capability to handle. I was confused to see the use of "Order Profile V2" as the reference to what I Believe to be PEPPOL BIS <order>. Maybe you should consider using the "normative" terms?

**Comment by clancger** [comment]
How about changing this view totally, and using the capability detail to populate a table as per example below? It would prob need a disclaimer as shown or similar.

![image](https://cloud.githubusercontent.com/assets/1429765/26348357/690bdff2-3fa4-11e7-8401-23a6282a33e7.png)

**PEPPOL Policy currently only registers PEPPOL Document RECEIVERS on the network**
Therefore the “send” capabilities are marked as n/a by default. 
If there is a "Yes" in the send section, in advance of the PEPPOL policy changing to include sender details, it is because a manual workaround has been implemented specific to this PEPPOL Participant, by their Service Provider

**Comment by phax** [comment]
Makes sense, as soon as the first update list of supported document types is available!
And below this standard list, the "additional document types" are listed???

**Comment by phax** [comment]
There is a codelist available now
